# Dockerfile_Flask

FROM python:3.10-bookworm

WORKDIR /app

# Set PYTHONPATH to include /app, ensuring 'backend' is discoverable
ENV PYTHONPATH=/app:$PYTHONPATH

# UPGRADE PIP
RUN pip install --upgrade pip

# Instala curl y otras dependencias del sistema si son necesarias
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl

# Create the /app/backend directory where your Python package will reside
RUN mkdir -p /app/backend

# Copy requirements.txt from the host's 'backend/' directory to '/app/backend/' in the container
COPY backend/requirements.txt /app/backend/

# Install Python dependencies from the copied requirements.txt
RUN pip install --no-cache-dir -r /app/backend/requirements.txt

# Install Tesseract OCR and language packs
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    tesseract-ocr \
    tesseract-ocr-spa \
    tesseract-ocr-eng \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the entire 'backend' application code from the host to '/app/backend/' in the container
# This ensures 'backend' is a top-level package inside /app, making imports like 'from backend.user_service' work.
COPY backend/ /app/backend/

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "backend.app:app"]