# backend/Dockerfile_Flask

# Usa la imagen base que ya estés utilizando (ej. python:3.9-slim-bookworm)
FROM python:3.10-slim-noble
# Puedes mantener 'slim-buster' si no necesita grandes dependencias

WORKDIR /app

# Instala curl y otras dependencias del sistema si son necesarias
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    tesseract-ocr \
    tesseract-ocr-spa \
    tesseract-ocr-eng \
    # Soporte para inglés
    # Limpiar el cache de apt para reducir el tamaño de la imagen
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY . .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]