# Dockerfile_celery

FROM python:3.10-bookworm

WORKDIR /app

# Set PYTHONPATH to include /app, ensuring 'backend' is discoverable
ENV PYTHONPATH=/app:$PYTHONPATH

# UPGRADE PIP
RUN pip install --upgrade pip

# Create the /app/backend directory
RUN mkdir -p /app/backend

# Copy requirements.txt from the host's 'backend/' directory to '/app/backend/' in the container
COPY backend/requirements.txt /app/backend/

# Install Python dependencies
RUN pip install --no-cache-dir -r /app/backend/requirements.txt \
    psycopg2-binary \
    celery \
    mobi \
    python-docx \
    openpyxl \
    python-pptx \
    Ebooklib \
    html2text \
    pytesseract \
    Pillow

# INSTALAR CALIBRE (ebook-convert) Y SUS DEPENDENCIAS
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    calibre \
    libfontconfig1 \
    libxrender1 \
    xvfb \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# INSTALAR TESSERACT OCR Y SUS PAQUETES DE IDIOMA
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    tesseract-ocr \
    tesseract-ocr-spa \
    tesseract-ocr-eng \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# INSTALAR CLAMAV Y ACTUALIZAR DEFINICIONES
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    clamav \
    clamav-freshclam \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Actualizar las definiciones de virus de ClamAV
RUN freshclam

# Copy the rest of your application from the host's 'backend/' directory to '/app/backend/' in the container
COPY backend/ /app/backend/