# backend/Dockerfile_Flask

# Usa la imagen base que ya estés utilizando (ej. python:3.9-slim-bookworm)
FROM python:3.9-slim-bookworm

WORKDIR /app

# Instala curl y otras dependencias del sistema si son necesarias
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
